version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 271202
      MYSQL_DATABASE: rbs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: php-apache
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/html/frontend

  web:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/html/frontend

volumes:
  db_data: